// frontend/src/App.tsx
import { useAppStore } from './stores/app'
import { Sidebar } from './components/Sidebar'
import { ChatView } from './components/Chat'
import { FileTransferView } from './components/FileTransfer'
import { FileReceiveDialog } from './components/Dialogs/FileReceiveDialog'
import { MessageSquare, FolderOpen } from 'lucide-react'
import { cn } from './lib/cn'

export function App() {
  const activeTab = useAppStore((s) => s.activeTab)
  const setActiveTab = useAppStore((s) => s.setActiveTab)

  return (
    <div className="flex h-screen bg-[#0a0a1a] text-[#e2e8f0]">
      <Sidebar />

      <main className="flex min-w-0 flex-1 flex-col">
        {/* Tab bar */}
        <div className="flex h-14 items-center border-b border-[#16213e] bg-[#1a1a2e]">
          <button
            type="button"
            onClick={() => setActiveTab('chat')}
            className={cn(
              'flex items-center gap-1.5 border-b-2 px-5 py-2.5 text-sm transition-colors',
              activeTab === 'chat'
                ? 'border-[#533483] text-[#e0e0e0]'
                : 'border-transparent text-[#888] hover:text-[#ccc]',
            )}
          >
            <MessageSquare className="h-4 w-4" /> Chat
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('files')}
            className={cn(
              'flex items-center gap-1.5 border-b-2 px-5 py-2.5 text-sm transition-colors',
              activeTab === 'files'
                ? 'border-[#533483] text-[#e0e0e0]'
                : 'border-transparent text-[#888] hover:text-[#ccc]',
            )}
          >
            <FolderOpen className="h-4 w-4" /> Files
          </button>
        </div>

        {/* Tab content */}
        <div className="flex min-h-0 flex-1 flex-col bg-[#16213e]">
          {activeTab === 'chat' ? <ChatView /> : <FileTransferView />}
        </div>
      </main>

      <FileReceiveDialog />
    </div>
  )
}

// frontend/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import ContactList from './views/ContactList.vue'
import ChatView from './views/ChatView.vue'
import FileTransfer from './views/FileTransfer.vue'

const activeTab = ref<'chat' | 'files'>('chat')
</script>

<template>
  <div class="app-layout">
    <ContactList />
    <div class="main-area">
      <div class="tab-bar">
        <button
          :class="['tab', { active: activeTab === 'chat' }]"
          @click="activeTab = 'chat'"
        >
          💬 Chat
        </button>
        <button
          :class="['tab', { active: activeTab === 'files' }]"
          @click="activeTab = 'files'"
        >
          📁 Files
        </button>
      </div>
      <ChatView v-if="activeTab === 'chat'" />
      <FileTransfer v-else />
    </div>
  </div>
</template>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body, #app {
  height: 100%;
  width: 100%;
  overflow: hidden;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #0a0a1a;
}
</style>

<style scoped>
.app-layout {
  display: flex;
  height: 100vh;
  width: 100vw;
}

.main-area {
  display: flex;
  flex-direction: column;
  flex: 1;
  min-width: 0;
}

.tab-bar {
  display: flex;
  background: #1a1a2e;
  border-bottom: 1px solid #16213e;
}

.tab {
  padding: 10px 20px;
  border: none;
  background: transparent;
  color: #888;
  font-size: 14px;
  cursor: pointer;
  border-bottom: 2px solid transparent;
  transition: all 0.15s;
}

.tab:hover {
  color: #ccc;
}

.tab.active {
  color: #e0e0e0;
  border-bottom-color: #533483;
}
</style>
